spring:
  application.name: restaurants

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KC_URL:http://localhost:8080}/realms/${KC_REALM:users_realm}

  datasource:
    url: ${DB_URL:jdbc:postgresql://host.docker.internal:9854/restaurants}
    username: ${DB_USER:restaurants_db_admin}
    password: ${DB_PASSWORD:restaurants_db_admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVICE_PORT:8082}

logging:
  level:
    root: ERROR
    org.springframework: INFO
    com.reservly: DEBUG

springdoc:
  api-docs:
    path: /docs/api-docs
  swagger-ui:
    path: /docs/swagger-ui
    try-it-out-enabled: true
    disable-swagger-default-url: true
    use-root-path: true